### ISSUE TITLE
LED color change invokes flash rewrite which is limited in number of times

### ISSUE THREAD

**Issue by evertvdp** [shellykauppa/plus-plug-spot-illuminator#3]
To start, thanks for creating this script and making it available. I want to use it for a similar use case, but based on actual conditions (e.g. solar production, network load).

Issue: The script changes the configuration continuously. The changes are stored in persistent memory (flash). The number of writes of the flash of a microcontroller is typically 100k - 1M (not confirmed by Shelly) --> this would mean that after 28 hours of use at 1Hz update rate, the flash could be 'worn out'.
When only changing it once every 15 minutes would lead to 25000 hours of use - which is still pretty limited (2.9 years).

Is there a way to change the LED color without performing a SetConfig?

**Comment by anttikuuskoski** [comment]
Hello @evertvdp, thanks for the report!

> Is there a way to change the LED color without performing a SetConfig?

To our knowledge (i.e. what's written on the [device API page](https://shelly-api-docs.shelly.cloud/gen2/Devices/Gen2/ShellyPlusPlugS), this is the only way to change the led lights.

I'm not certain how high the risk is in actual use. Unless I'm mistaken, the write limit is counted for each cell separately so it is highly dependent on the method of writing the memory (i.e. whether the same cell is always used or whether the memory location is rotated etc.). If you have any pointers to any confirmed information regarding Shelly flash operations, we'd appreciate the information.  

Unfortunately, the worst should be expected regarding memory usage. What might reduce the write rate significantly is to ensure that no unnecessary writes are performed. In practice, a deep comparison must be made between the new ui config and existing one around [L213](https://github.com/shellykauppa/plus-plug-spot-illuminator/blob/1ae3cf2d5217f82963723fdb2fcfda12bc6fa518/shelly/index.js#L213) and the config written only if there's an actual change. Pull requests are very welcome but we'll try to implement this eventually should none appear :) This approach should work for your use case as well.

**Comment by evertvdp** [comment]
I just submitted a feature-request for having a scripting-interface or RPC to the LEDs to the developers at Shelly without using SetConfig. Additionally, I asked for them to confirm/refute the limit in number of writes.
When I get a reply from them, I will post it here.

Cheers from NL!
Evert

**Comment by anttikuuskoski** [comment]
The issue was resolved version [2.1.0](https://github.com/shellykauppa/plug-s-spot-illuminator/releases/tag/2.1.0) by ensuring that configuration is updated only when necessary, i.e. when price has changed.
